// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.28.0";

// src/lib/mcp/tools/list-groups.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z } from "npm:zod@^3.23.8";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.54.0";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
function requireAuth(ctx) {
  if (!ctx.isAuthenticated()) {
    throw new Error("Not authenticated. Sign in to Diviso to use this tool.");
  }
  return ctx.getUserId();
}
function textResult(payload) {
  return { content: [{ type: "text", text: JSON.stringify(payload) }] };
}
function errorResult(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}

// src/lib/mcp/tools/list-groups.ts
var list_groups_default = defineTool({
  name: "list_groups",
  title: "List groups",
  description: "List the Diviso expense-sharing groups the signed-in user belongs to, with id, name, currency and status.",
  inputSchema: {
    status: z.enum(["active", "finished", "closed", "all"]).optional().describe("Filter by group status. Defaults to all.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status }, ctx) => {
    try {
      requireAuth(ctx);
      const supabase = supabaseForUser(ctx);
      let query = supabase.from("groups").select("id, name, currency, group_type, status, created_at").order("created_at", { ascending: false }).limit(100);
      if (status && status !== "all") query = query.eq("status", status);
      const { data, error } = await query;
      if (error) return errorResult(error.message);
      return textResult({ groups: data ?? [] });
    } catch (e) {
      return errorResult(e instanceof Error ? e.message : String(e));
    }
  }
});

// src/lib/mcp/tools/get-group.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z2 } from "npm:zod@^3.23.8";
var get_group_default = defineTool2({
  name: "get_group",
  title: "Get group details",
  description: "Get one Diviso group with its members and totals. Use list_groups first to find the group id.",
  inputSchema: {
    group_id: z2.string().uuid().describe("The group's UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ group_id }, ctx) => {
    try {
      requireAuth(ctx);
      const supabase = supabaseForUser(ctx);
      const { data: group, error: groupError } = await supabase.from("groups").select("id, name, currency, group_type, status, created_at").eq("id", group_id).maybeSingle();
      if (groupError) return errorResult(groupError.message);
      if (!group) return errorResult("Group not found or not accessible.");
      const { data: members } = await supabase.from("group_members").select("id, user_id, display_name, role, status").eq("group_id", group_id).is("archived_at", null);
      const { data: expenses } = await supabase.from("expenses").select("amount").eq("group_id", group_id);
      const total = (expenses ?? []).reduce((sum, e) => sum + Number(e.amount ?? 0), 0);
      return textResult({
        group,
        members: members ?? [],
        expense_count: expenses?.length ?? 0,
        total_spent: total
      });
    } catch (e) {
      return errorResult(e instanceof Error ? e.message : String(e));
    }
  }
});

// src/lib/mcp/tools/list-expenses.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z3 } from "npm:zod@^3.23.8";
var list_expenses_default = defineTool3({
  name: "list_expenses",
  title: "List expenses",
  description: "List expenses in a Diviso group, newest first, including amount, payer and description.",
  inputSchema: {
    group_id: z3.string().uuid().describe("The group's UUID."),
    limit: z3.number().int().min(1).max(100).optional().describe("Max rows, default 25.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ group_id, limit }, ctx) => {
    try {
      requireAuth(ctx);
      const supabase = supabaseForUser(ctx);
      const { data, error } = await supabase.from("expenses").select("id, amount, currency, description, payer_id, spent_at, status, created_at").eq("group_id", group_id).order("spent_at", { ascending: false }).limit(limit ?? 25);
      if (error) return errorResult(error.message);
      return textResult({ expenses: data ?? [] });
    } catch (e) {
      return errorResult(e instanceof Error ? e.message : String(e));
    }
  }
});

// src/lib/mcp/tools/list-balances.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z4 } from "npm:zod@^3.23.8";
var list_balances_default = defineTool4({
  name: "list_balances",
  title: "List group balances",
  description: "Compute who owes whom in a Diviso group: per-member paid, share and net balance (positive = owed money).",
  inputSchema: {
    group_id: z4.string().uuid().describe("The group's UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ group_id }, ctx) => {
    try {
      requireAuth(ctx);
      const supabase = supabaseForUser(ctx);
      const { data: group } = await supabase.from("groups").select("currency").eq("id", group_id).maybeSingle();
      const { data: members, error: membersError } = await supabase.from("group_members").select("user_id, display_name").eq("group_id", group_id).is("archived_at", null);
      if (membersError) return errorResult(membersError.message);
      const { data: expenses, error: expensesError } = await supabase.from("expenses").select("id, amount, payer_id").eq("group_id", group_id);
      if (expensesError) return errorResult(expensesError.message);
      const expenseIds = (expenses ?? []).map((e) => e.id);
      const { data: splits } = expenseIds.length ? await supabase.from("expense_splits").select("expense_id, member_id, share_amount").in("expense_id", expenseIds) : { data: [] };
      const paid = /* @__PURE__ */ new Map();
      for (const e of expenses ?? []) {
        if (!e.payer_id) continue;
        paid.set(e.payer_id, (paid.get(e.payer_id) ?? 0) + Number(e.amount ?? 0));
      }
      const owes = /* @__PURE__ */ new Map();
      for (const s of splits ?? []) {
        owes.set(s.member_id, (owes.get(s.member_id) ?? 0) + Number(s.share_amount ?? 0));
      }
      const balances = (members ?? []).filter((m) => m.user_id).map((m) => {
        const p = paid.get(m.user_id) ?? 0;
        const o = owes.get(m.user_id) ?? 0;
        return {
          user_id: m.user_id,
          name: m.display_name,
          paid: Math.round(p * 100) / 100,
          share: Math.round(o * 100) / 100,
          net: Math.round((p - o) * 100) / 100
        };
      });
      return textResult({ currency: group?.currency ?? "SAR", balances });
    } catch (e) {
      return errorResult(e instanceof Error ? e.message : String(e));
    }
  }
});

// src/lib/mcp/tools/list-settlements.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z5 } from "npm:zod@^3.23.8";
var list_settlements_default = defineTool5({
  name: "list_settlements",
  title: "List settlements",
  description: "List settlements (payments between members) in a Diviso group, optionally filtered by status.",
  inputSchema: {
    group_id: z5.string().uuid().describe("The group's UUID."),
    status: z5.enum(["pending", "confirmed", "disputed", "all"]).optional().describe("Filter by settlement status. Defaults to all.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ group_id, status }, ctx) => {
    try {
      requireAuth(ctx);
      const supabase = supabaseForUser(ctx);
      let query = supabase.from("settlements").select(
        "id, amount, currency, from_user_id, to_user_id, status, settlement_type, note, created_at, confirmed_at"
      ).eq("group_id", group_id).order("created_at", { ascending: false }).limit(100);
      if (status && status !== "all") query = query.eq("status", status);
      const { data, error } = await query;
      if (error) return errorResult(error.message);
      return textResult({ settlements: data ?? [] });
    } catch (e) {
      return errorResult(e instanceof Error ? e.message : String(e));
    }
  }
});

// src/lib/mcp/tools/create-expense.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z6 } from "npm:zod@^3.23.8";
var create_expense_default = defineTool6({
  name: "create_expense",
  title: "Add an expense",
  description: "Add an expense to a Diviso group and split it equally between the active members. Ask the user to confirm the amount and description first.",
  inputSchema: {
    group_id: z6.string().uuid().describe("The group's UUID."),
    amount: z6.number().positive().describe("Total amount of the expense."),
    description: z6.string().min(1).max(200).describe("What the expense was for."),
    payer_id: z6.string().uuid().optional().describe("User id of who paid. Defaults to the signed-in user."),
    spent_at: z6.string().optional().describe("ISO date of the expense. Defaults to now.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ group_id, amount, description, payer_id, spent_at }, ctx) => {
    try {
      const userId = requireAuth(ctx);
      const supabase = supabaseForUser(ctx);
      const { data: group, error: groupError } = await supabase.from("groups").select("id, currency, status").eq("id", group_id).maybeSingle();
      if (groupError) return errorResult(groupError.message);
      if (!group) return errorResult("Group not found or not accessible.");
      const { data: members, error: membersError } = await supabase.from("group_members").select("user_id").eq("group_id", group_id).eq("status", "active").is("archived_at", null);
      if (membersError) return errorResult(membersError.message);
      const participants = (members ?? []).map((m) => m.user_id).filter((id) => Boolean(id));
      if (participants.length === 0) {
        return errorResult("This group has no active members to split the expense between.");
      }
      const { data: expense, error: expenseError } = await supabase.from("expenses").insert({
        group_id,
        amount,
        currency: group.currency,
        description,
        created_by: userId,
        payer_id: payer_id ?? userId,
        spent_at: spent_at ?? (/* @__PURE__ */ new Date()).toISOString()
      }).select("id, amount, currency, description, payer_id, spent_at").single();
      if (expenseError) return errorResult(expenseError.message);
      const share = Math.round(amount / participants.length * 100) / 100;
      const splits = participants.map((memberId, index) => ({
        expense_id: expense.id,
        member_id: memberId,
        // Push any rounding remainder onto the first participant.
        share_amount: index === 0 ? Math.round((amount - share * (participants.length - 1)) * 100) / 100 : share
      }));
      const { error: splitsError } = await supabase.from("expense_splits").insert(splits);
      if (splitsError) {
        await supabase.from("expenses").delete().eq("id", expense.id);
        return errorResult(`Could not split the expense: ${splitsError.message}`);
      }
      return textResult({ expense, split_between: participants.length, share_per_person: share });
    } catch (e) {
      return errorResult(e instanceof Error ? e.message : String(e));
    }
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "diviso",
  title: "Diviso",
  version: "1.0.0",
  instructions: "Diviso is a group expense-splitting app. Every tool acts on behalf of the signed-in Diviso user. Use list_groups to find a group id, then get_group, list_expenses, list_balances and list_settlements to read its data, and create_expense to add a shared expense that is split equally between the active members. Amounts are in the group's own currency (usually SAR).",
  auth: auth.oauth.issuer({
    issuer: "https://iwthriddasxzbjddpzzf.supabase.co/auth/v1",
    // Supabase GoTrue mints project-wide `aud: "authenticated"` tokens.
    acceptedAudiences: ["authenticated"],
    resourceName: "Diviso",
    resourceDocumentation: "https://diviso.app/support"
  }),
  tools: [
    list_groups_default,
    get_group_default,
    list_expenses_default,
    list_balances_default,
    list_settlements_default,
    create_expense_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.28.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
